/*

Problem 29

Consider all integer combinations of a^b for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:

22=4, 23=8, 24=16, 25=32
32=9, 33=27, 34=81, 35=243
42=16, 43=64, 44=256, 45=1024
52=25, 53=125, 54=625, 55=3125

If they are then placed in numerical order, with any repeats removed,
we get the following sequence of 15 distinct terms:

4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125

How many distinct terms are in the sequence generated by a^b
for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

*/

// gcc p029.c btree.c -o p029

#include <stdio.h>
#include "btree.h"
#include <math.h>

#define N 100

long int a_p_b(int a, int b) {
	long int p = a;
	for (int i=1; i<b; i++) {
		p = p * a;
	}
	return p;
}

int main(int argc, char *argv[]) {

	struct node *root = 0; // root node of the tree
	double x;
	for (int a=2; a<=N; a++) {
		for (int b=2; b<=N; b++) {
//			x = a_p_b(a,b);
			x = pow(a,b);
//			printf("%d^%d = %ld\n", a,b,x);
			insert(x, &root);
		}
	}

//	print_tree(root);
	printf("for N=%d there are %d distinct terms\n", N, count_tree(root)-1);

	destroy_tree(root);

	return 0;
}










